[package]
name = "scripty_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
once_cell = "1.9"
serde = { version = "1.0", features = ["derive"] }
