[package]
name = "scripty_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "=0.5.11"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
