[package]
name = "scripty_audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4"
tracing = "0.1"
num_cpus = "1.13"
once_cell = "1.9"
coqui-stt = "0.1"
threadpool = "1.8"
dasp_signal = "0.11"
scripty_config = { path = "../scripty_config" }
tokio = { version = "1.16", features = ["sync"] }
dasp_interpolate = { version = "0.11", features = ["linear"] }
